<$PLAN9/src/mkhdr

TARG=parser_test parseurl_test fetch_url_test html_test color_test css_test layout_test

# source file providing fetch_url implementation
FETCHER_SRC=../src/fetcher.c

parser_test: parser_test.$O parser.$O
    $LD -o $target parser_test.$O parser.$O

parser_test.$O: parser_test.c ../src/parser.h
    $CC -I../src -c -o $target parser_test.c

parser.$O: ../src/parser.c ../src/parser.h
    $CC -I../src -c -o $target ../src/parser.c

parseurl_test: parseurl_test.$O
    $LD -o $target parseurl_test.$O

parseurl_test.$O: parseurl_test.c
    $CC -I../src -c -o $target parseurl_test.c

fetch_url_test: fetch_url_test.$O fetcher.$O
    $LD -o $target fetch_url_test.$O fetcher.$O

fetch_url_test.$O: fetch_url_test.c ../src/fetcher.h
    $CC -I../src -c -o $target fetch_url_test.c

fetcher.$O: $FETCHER_SRC ../src/fetcher.h
    $CC -I../src -c -o $target $FETCHER_SRC

html_test: html_test.$O html.$O
    $LD -o $target html_test.$O html.$O

html_test.$O: html_test.c ../src/html.h
    $CC -I../src -c -o $target html_test.c

html.$O: ../src/html.c ../src/html.h
    $CC -I../src -c -o $target ../src/html.c

color_test: color_test.$O color.$O
    $LD -o $target color_test.$O color.$O

color_test.$O: color_test.c ../src/color.h
    $CC -I../src -c -o $target color_test.c

color.$O: ../src/color.c ../src/color.h
    $CC -I../src -c -o $target ../src/color.c

css_test: css_test.$O css.$O color.$O
    $LD -o $target css_test.$O css.$O color.$O

css_test.$O: css_test.c ../src/css.h ../src/color.h
    $CC -I../src -c -o $target css_test.c

css.$O: ../src/css.c ../src/css.h ../src/color.h
    $CC -I../src -c -o $target ../src/css.c

layout_test: layout_test.$O layout.$O css.$O color.$O
    $LD -o $target layout_test.$O layout.$O css.$O color.$O

layout_test.$O: layout_test.c ../src/layout.h ../src/css.h ../src/color.h
    $CC -I../src -c -o $target layout_test.c

layout.$O: ../src/layout.c ../src/layout.h ../src/css.h ../src/color.h
    $CC -I../src -c -o $target ../src/layout.c

clean:V:
    rm -f *.[$OS] $TARG parser.$O fetcher.$O html.$O color.$O css.$O layout.$O
